ifneq ($(filter 3.%,$(MAKE_VERSION)),)
$(error GNU Make version 4.x or higher is required. You are using version $(MAKE_VERSION). Please upgrade your Make installation.)
endif

.DEFAULT_GOAL := all
ROOT_MAKEFILE := $(abspath $(lastword $(MAKEFILE_LIST)))
PROJECT_ROOT := $(patsubst %/,%,$(dir $(ROOT_MAKEFILE)))
GO_TARGET_PREFIX := go.
SWIFT_TARGET_PREFIX := swift.
MAKEFILE_TARGET_PREFIXES := $(MAKEFILE_TARGET_PREFIXES) SWIFT_TARGET_PREFIX
SWIFT_DAG__Server := root
GO_MODULE_SLUGS_NO_PACKAGES ?= hack.google-api-linter
GO_MODULE_SLUGS_NO_UPDATE ?= hack.google-api-linter
# excludes generated files + files that are largely unchanged from upstream
SWIFT_PACKAGE_FILES_NO_LINT_OR_FORMAT ?= \
./Server/Sources/MacosUseProto/% \
./Sources/VisualInputTool/main.swift \
./Sources/TraversalTool/main.swift \
./Sources/MacosUseSDK/InputController.swift \
./Sources/MacosUseSDK/HighlightInput.swift \
./Sources/MacosUseSDK/CombinedActions.swift \
./Sources/MacosUseSDK/DrawVisuals.swift \
./Sources/MacosUseSDK/AppOpener.swift \
./Sources/MacosUseSDK/ActionCoordinator.swift \
./Sources/MacosUseSDK/AccessibilityTraversal.swift \
./Sources/InputControllerTool/main.swift \
./Sources/HighlightTraversalTool/main.swift \
./Sources/AppOpenerTool/main.swift \
./Sources/ActionTool/main.swift \
./Tests/MacosUseSDKTests/CombinedActionsDiffTests.swift \
./Tests/MacosUseSDKTests/CombinedActionsFocusVisualizationTests.swift
SWIFT_PACKAGE_FILES_NO_LINT ?= $(SWIFT_PACKAGE_FILES_NO_LINT_OR_FORMAT)
SWIFT_PACKAGE_FILES_NO_FORMAT ?= $(SWIFT_PACKAGE_FILES_NO_LINT_OR_FORMAT)

-include $(PROJECT_ROOT)/config.mk
include $(PROJECT_ROOT)/make/go.mk
include $(PROJECT_ROOT)/make/swift.mk
include $(PROJECT_ROOT)/make/buf.mk

##@ Core Targets

.PHONY: all
all: proto-lint ## Run a full build of the project.
	$(MAKE) --no-print-directory swift.all
	ls -alh $(PROJECT_ROOT)/Server/.build/release/
	$(MAKE) --no-print-directory go.all GO_TEST_FLAGS=$(call escape_command_arg,$(if $(filter -count,$(GO_TEST_FLAGS))$(filter -count=%,$(GO_TEST_FLAGS)),$(GO_TEST_FLAGS),$(GO_TEST_FLAGS) -count=1))

.PHONY: clean
clean: go.clean swift.clean ## Tidy up local files generated by the build.

.PHONY: fmt
fmt: go.fmt buf.format swift.format ## Format all source files.

.PHONY: lint
lint: go.lint proto-lint swift.lint ## Lint all source files.

.PHONY: fix
fix: go.fix swift.fix ## Apply automatic fixes to source files.
	@$(MAKE) --no-print-directory fmt

.PHONY: generate
generate: ## Generate all code.
	@$(MAKE) --no-print-directory buf.generate
	@$(MAKE) --no-print-directory go.generate
	@$(MAKE) --no-print-directory fmt

.PHONY: gen
gen: generate ## Alias for 'generate'.

.PHONY: update
update: ## Update all dependencies.
	@$(MAKE) --no-print-directory buf.update
	@$(MAKE) --no-print-directory go.update
	@$(MAKE) --no-print-directory generate

.PHONY: proto-lint
proto-lint: google-api-linter buf.lint ## Run proto linters e.g. google-api-linter, buf lint.

.PHONY: google-api-linter
google-api-linter: ## Lint the proto files.
	hack/google-api-linter.sh

##@ -- End of root Makefile --
