.DEFAULT_GOAL := all
ROOT_MAKEFILE := $(abspath $(lastword $(MAKEFILE_LIST)))
PROJECT_ROOT := $(patsubst %/,%,$(dir $(ROOT_MAKEFILE)))
GO_TARGET_PREFIX := go.
SWIFT_TARGET_PREFIX := swift.

-include $(PROJECT_ROOT)/config.mk
include $(PROJECT_ROOT)/make/go.mk
include $(PROJECT_ROOT)/make/swift.mk

##@ Core Targets

.PHONY: all
all: go.all swift.all ## Run a full build of the project.

.PHONY: clean
clean: go.clean swift.clean ## Tidy up local files generated by the build.

##@ -- End of root Makefile --
