// Copyright 2025 Joseph Cumines
//
// Condition values for defining criteria to trigger actions

syntax = "proto3";

package exactmac.v1;

import "google/api/field_behavior.proto";

option go_package = "github.com/joeycumines/ExactMac/gen/go/exactmac/v1;exactmacpb";
option java_multiple_files = true;
option java_outer_classname = "ConditionProto";
option java_package = "io.github.joeycumines.exactmac.v1";

// Attribute condition for waiting.
message AttributeCondition {
  // Attribute name.
  string attribute = 1 [(google.api.field_behavior) = REQUIRED];

  // Expected attribute value.
  string value = 2 [(google.api.field_behavior) = REQUIRED];
}
