// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: exactmac/v1/element.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Joseph Cumines
//
// Ephemeral accessibility element resource

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A UI element retained from an Accessibility traversal. Element resources are
/// ephemeral: clients must rediscover them after expiry or server restart.
public nonisolated struct Exactmac_V1_Element: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Canonical resource name in the format
  /// "applications/{application}/elements/{element}". The element segment is
  /// an opaque server-generated ID valid only while this resource is retained.
  public var name: String = String()

  /// The accessibility role of the element (for example, button or text field).
  public var role: String = String()

  /// Text content of the element, if any.
  public var text: String {
    get {_text ?? String()}
    set {_text = newValue}
  }
  /// Returns true if `text` has been explicitly set.
  public var hasText: Bool {self._text != nil}
  /// Clears the value of `text`. Subsequent reads from it will return its default value.
  public mutating func clearText() {self._text = nil}

  /// X coordinate in Global Display Coordinates (top-left origin, Y increases downward).
  public var x: Double {
    get {_x ?? 0}
    set {_x = newValue}
  }
  /// Returns true if `x` has been explicitly set.
  public var hasX: Bool {self._x != nil}
  /// Clears the value of `x`. Subsequent reads from it will return its default value.
  public mutating func clearX() {self._x = nil}

  /// Y coordinate in Global Display Coordinates (top-left origin, Y increases downward).
  public var y: Double {
    get {_y ?? 0}
    set {_y = newValue}
  }
  /// Returns true if `y` has been explicitly set.
  public var hasY: Bool {self._y != nil}
  /// Clears the value of `y`. Subsequent reads from it will return its default value.
  public mutating func clearY() {self._y = nil}

  /// Width of the element in pixels.
  public var width: Double {
    get {_width ?? 0}
    set {_width = newValue}
  }
  /// Returns true if `width` has been explicitly set.
  public var hasWidth: Bool {self._width != nil}
  /// Clears the value of `width`. Subsequent reads from it will return its default value.
  public mutating func clearWidth() {self._width = nil}

  /// Height of the element in pixels.
  public var height: Double {
    get {_height ?? 0}
    set {_height = newValue}
  }
  /// Returns true if `height` has been explicitly set.
  public var hasHeight: Bool {self._height != nil}
  /// Clears the value of `height`. Subsequent reads from it will return its default value.
  public mutating func clearHeight() {self._height = nil}

  /// Opaque ephemeral ID for request fields that already carry the application parent.
  public var elementID: String = String()

  /// Whether the element is enabled for interaction.
  public var enabled: Bool {
    get {_enabled ?? false}
    set {_enabled = newValue}
  }
  /// Returns true if `enabled` has been explicitly set.
  public var hasEnabled: Bool {self._enabled != nil}
  /// Clears the value of `enabled`. Subsequent reads from it will return its default value.
  public mutating func clearEnabled() {self._enabled = nil}

  /// Whether the element has keyboard focus.
  public var focused: Bool {
    get {_focused ?? false}
    set {_focused = newValue}
  }
  /// Returns true if `focused` has been explicitly set.
  public var hasFocused: Bool {self._focused != nil}
  /// Clears the value of `focused`. Subsequent reads from it will return its default value.
  public mutating func clearFocused() {self._focused = nil}

  /// Hierarchy path indices from the traversal root to this element.
  public var pathIndices: [Int32] = []

  /// Additional Accessibility attributes represented as key-value pairs.
  public var attributes: Dictionary<String,String> = [:]

  /// Available Accessibility action names.
  public var actions: [String] = []

  /// Owning application resource (for example, "applications/com.apple.TextEdit-abc123").
  /// This is the canonical owner at discovery time; a stale element must be re-resolved.
  public var application: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _text: String? = nil
  fileprivate var _x: Double? = nil
  fileprivate var _y: Double? = nil
  fileprivate var _width: Double? = nil
  fileprivate var _height: Double? = nil
  fileprivate var _enabled: Bool? = nil
  fileprivate var _focused: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "exactmac.v1"

nonisolated extension Exactmac_V1_Element: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Element"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}role\0\u{1}text\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0\u{3}element_id\0\u{1}enabled\0\u{1}focused\0\u{3}path_indices\0\u{1}attributes\0\u{1}actions\0\u{1}application\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.role) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._text) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._x) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self._y) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._width) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._height) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.elementID) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._enabled) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._focused) }()
      case 11: try { try decoder.decodeRepeatedInt32Field(value: &self.pathIndices) }()
      case 12: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.attributes) }()
      case 13: try { try decoder.decodeRepeatedStringField(value: &self.actions) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self.application) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.role.isEmpty {
      try visitor.visitSingularStringField(value: self.role, fieldNumber: 2)
    }
    try { if let v = self._text {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._x {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._y {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._width {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._height {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    if !self.elementID.isEmpty {
      try visitor.visitSingularStringField(value: self.elementID, fieldNumber: 8)
    }
    try { if let v = self._enabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._focused {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    if !self.pathIndices.isEmpty {
      try visitor.visitPackedInt32Field(value: self.pathIndices, fieldNumber: 11)
    }
    if !self.attributes.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.attributes, fieldNumber: 12)
    }
    if !self.actions.isEmpty {
      try visitor.visitRepeatedStringField(value: self.actions, fieldNumber: 13)
    }
    if !self.application.isEmpty {
      try visitor.visitSingularStringField(value: self.application, fieldNumber: 14)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_Element, rhs: Exactmac_V1_Element) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.role != rhs.role {return false}
    if lhs._text != rhs._text {return false}
    if lhs._x != rhs._x {return false}
    if lhs._y != rhs._y {return false}
    if lhs._width != rhs._width {return false}
    if lhs._height != rhs._height {return false}
    if lhs.elementID != rhs.elementID {return false}
    if lhs._enabled != rhs._enabled {return false}
    if lhs._focused != rhs._focused {return false}
    if lhs.pathIndices != rhs.pathIndices {return false}
    if lhs.attributes != rhs.attributes {return false}
    if lhs.actions != rhs.actions {return false}
    if lhs.application != rhs.application {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
