// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: exactmac/v1/input.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Joseph Cumines
//
// Input resource definition

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A resource representing an input action that was or will be executed.
/// Inputs form an execution timeline under an application or the explicit
/// desktop wildcard parent while target records the exact delivery authority.
public nonisolated struct Exactmac_V1_Input: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Resource name in the format "applications/{application}/inputs/{input}".
  /// Desktop-wide input uses the explicit wildcard application segment "-".
  public var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// The specific action to perform or that was performed.
  public var action: Exactmac_V1_InputAction {
    get {_storage._action ?? Exactmac_V1_InputAction()}
    set {_uniqueStorage()._action = newValue}
  }
  /// Returns true if `action` has been explicitly set.
  public var hasAction: Bool {_storage._action != nil}
  /// Clears the value of `action`. Subsequent reads from it will return its default value.
  public mutating func clearAction() {_uniqueStorage()._action = nil}

  /// Current state of the input.
  public var state: Exactmac_V1_Input.State {
    get {_storage._state}
    set {_uniqueStorage()._state = newValue}
  }

  /// When the input was created.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {_storage._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {_uniqueStorage()._createTime = nil}

  /// When the input completed (success or failure).
  public var completeTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._completeTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._completeTime = newValue}
  }
  /// Returns true if `completeTime` has been explicitly set.
  public var hasCompleteTime: Bool {_storage._completeTime != nil}
  /// Clears the value of `completeTime`. Subsequent reads from it will return its default value.
  public mutating func clearCompleteTime() {_uniqueStorage()._completeTime = nil}

  /// Error message if the input failed.
  public var error: String {
    get {_storage._error}
    set {_uniqueStorage()._error = newValue}
  }

  /// Exact authority and coordinate scope selected for this input.
  public var target: Exactmac_V1_InputTarget {
    get {_storage._target ?? Exactmac_V1_InputTarget()}
    set {_uniqueStorage()._target = newValue}
  }
  /// Returns true if `target` has been explicitly set.
  public var hasTarget: Bool {_storage._target != nil}
  /// Clears the value of `target`. Subsequent reads from it will return its default value.
  public mutating func clearTarget() {_uniqueStorage()._target = nil}

  /// Truthful delivery commitment recorded after execution settles.
  public var deliveryResult: Exactmac_V1_InputDeliveryResult {
    get {_storage._deliveryResult ?? Exactmac_V1_InputDeliveryResult()}
    set {_uniqueStorage()._deliveryResult = newValue}
  }
  /// Returns true if `deliveryResult` has been explicitly set.
  public var hasDeliveryResult: Bool {_storage._deliveryResult != nil}
  /// Clears the value of `deliveryResult`. Subsequent reads from it will return its default value.
  public mutating func clearDeliveryResult() {_uniqueStorage()._deliveryResult = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// State of an input action.
  public nonisolated enum State: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// Default unspecified state.
    case unspecified // = 0

    /// Input is pending execution.
    case pending // = 1

    /// Input is currently executing.
    case executing // = 2

    /// Input completed successfully.
    case completed // = 3

    /// Input failed with an error.
    case failed // = 4

    /// Input was cancelled before execution or while its owned cleanup settled.
    case cancelled // = 5
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .executing
      case 3: self = .completed
      case 4: self = .failed
      case 5: self = .cancelled
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .executing: return 2
      case .completed: return 3
      case .failed: return 4
      case .cancelled: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Exactmac_V1_Input.State] = [
      .unspecified,
      .pending,
      .executing,
      .completed,
      .failed,
      .cancelled,
    ]

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Exact delivery authority for an input action.
public nonisolated struct Exactmac_V1_InputTarget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var destination: Exactmac_V1_InputTarget.OneOf_Destination? = nil

  /// Exact running application resource.
  public var application: String {
    get {
      if case .application(let v)? = destination {return v}
      return String()
    }
    set {destination = .application(newValue)}
  }

  /// Exact opaque window resource.
  public var window: String {
    get {
      if case .window(let v)? = destination {return v}
      return String()
    }
    set {destination = .window(newValue)}
  }

  /// Exact display resource.
  public var display: String {
    get {
      if case .display(let v)? = destination {return v}
      return String()
    }
    set {destination = .display(newValue)}
  }

  /// Explicit authorization for the active desktop union.
  public var desktop: Bool {
    get {
      if case .desktop(let v)? = destination {return v}
      return false
    }
    set {destination = .desktop(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Destination: Equatable, Sendable {
    /// Exact running application resource.
    case application(String)
    /// Exact opaque window resource.
    case window(String)
    /// Exact display resource.
    case display(String)
    /// Explicit authorization for the active desktop union.
    case desktop(Bool)

  }

  public init() {}
}

/// Delivery truth for one settled input transaction.
public nonisolated struct Exactmac_V1_InputDeliveryResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Delivery commitment after execution and cleanup settle.
  public var commitment: Exactmac_V1_InputDeliveryResult.Commitment = .unspecified

  /// Number of events whose post operation was invoked.
  public var postedEventCount: Int32 = 0

  /// Whether delivery on the selected application/window/display/desktop route
  /// was observed rather than inferred from a void posting API.
  public var routedDeliveryObserved: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Degree to which the requested action is known to have reached a physical
  /// input sink.
  public nonisolated enum Commitment: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// The server has no usable delivery classification.
    case unspecified // = 0

    /// No requested physical effect reached an operating-system sink.
    case noEffect // = 1

    /// At least one requested physical effect may have reached an
    /// operating-system sink, but complete routed event delivery and safety
    /// cleanup could not be proved.
    case possiblyCommitted // = 2

    /// Every requested event reached the selected route and every release
    /// obligation settled.
    case committedAndSettled // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .noEffect
      case 2: self = .possiblyCommitted
      case 3: self = .committedAndSettled
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .noEffect: return 1
      case .possiblyCommitted: return 2
      case .committedAndSettled: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Exactmac_V1_InputDeliveryResult.Commitment] = [
      .unspecified,
      .noEffect,
      .possiblyCommitted,
      .committedAndSettled,
    ]

  }

  public init() {}
}

/// Specification of an input action.
public nonisolated struct Exactmac_V1_InputAction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Whether to show visual feedback during execution.
  public var visualFeedback: Bool = false

  /// Duration of visual feedback in seconds.
  public var animationDuration: Double = 0

  /// The specific input type and parameters.
  public var inputType: Exactmac_V1_InputAction.OneOf_InputType? = nil

  /// Mouse click action.
  public var mouseClick: Exactmac_V1_MouseClick {
    get {
      if case .mouseClick(let v)? = inputType {return v}
      return Exactmac_V1_MouseClick()
    }
    set {inputType = .mouseClick(newValue)}
  }

  /// Text input action.
  public var textInput: Exactmac_V1_TextInput {
    get {
      if case .textInput(let v)? = inputType {return v}
      return Exactmac_V1_TextInput()
    }
    set {inputType = .textInput(newValue)}
  }

  /// Key press action.
  public var keyPress: Exactmac_V1_KeyPress {
    get {
      if case .keyPress(let v)? = inputType {return v}
      return Exactmac_V1_KeyPress()
    }
    set {inputType = .keyPress(newValue)}
  }

  /// Mouse move action.
  public var mouseMove: Exactmac_V1_MouseMove {
    get {
      if case .mouseMove(let v)? = inputType {return v}
      return Exactmac_V1_MouseMove()
    }
    set {inputType = .mouseMove(newValue)}
  }

  /// Mouse drag action.
  public var mouseDrag: Exactmac_V1_MouseDrag {
    get {
      if case .mouseDrag(let v)? = inputType {return v}
      return Exactmac_V1_MouseDrag()
    }
    set {inputType = .mouseDrag(newValue)}
  }

  /// Scroll action.
  public var scrollAction: Exactmac_V1_Scroll {
    get {
      if case .scrollAction(let v)? = inputType {return v}
      return Exactmac_V1_Scroll()
    }
    set {inputType = .scrollAction(newValue)}
  }

  /// Hover action.
  public var hoverAction: Exactmac_V1_Hover {
    get {
      if case .hoverAction(let v)? = inputType {return v}
      return Exactmac_V1_Hover()
    }
    set {inputType = .hoverAction(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The specific input type and parameters.
  public nonisolated enum OneOf_InputType: Equatable, Sendable {
    /// Mouse click action.
    case mouseClick(Exactmac_V1_MouseClick)
    /// Text input action.
    case textInput(Exactmac_V1_TextInput)
    /// Key press action.
    case keyPress(Exactmac_V1_KeyPress)
    /// Mouse move action.
    case mouseMove(Exactmac_V1_MouseMove)
    /// Mouse drag action.
    case mouseDrag(Exactmac_V1_MouseDrag)
    /// Scroll action.
    case scrollAction(Exactmac_V1_Scroll)
    /// Hover action.
    case hoverAction(Exactmac_V1_Hover)

  }

  public init() {}
}

/// Mouse click action.
///
/// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
/// See exactmac.type.Point message documentation for detailed coordinate system explanation.
public nonisolated struct Exactmac_V1_MouseClick: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Position to click in Global Display Coordinates.
  /// This uses the same coordinate system as Window.bounds, allowing direct use of
  /// window coordinates for click targets.
  public var position: Exactmac_Type_Point {
    get {_position ?? Exactmac_Type_Point()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  /// Click type.
  public var clickType: Exactmac_V1_MouseClick.ClickType {
    get {_clickType ?? .unspecified}
    set {_clickType = newValue}
  }
  /// Returns true if `clickType` has been explicitly set.
  public var hasClickType: Bool {self._clickType != nil}
  /// Clears the value of `clickType`. Subsequent reads from it will return its default value.
  public mutating func clearClickType() {self._clickType = nil}

  /// Number of clicks (1 for single, 2 for double, etc.).
  public var clickCount: Int32 {
    get {_clickCount ?? 0}
    set {_clickCount = newValue}
  }
  /// Returns true if `clickCount` has been explicitly set.
  public var hasClickCount: Bool {self._clickCount != nil}
  /// Clears the value of `clickCount`. Subsequent reads from it will return its default value.
  public mutating func clearClickCount() {self._clickCount = nil}

  /// Modifier keys applied atomically to every click event.
  public var modifiers: [Exactmac_V1_KeyPress.Modifier] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Click type enumeration.
  public nonisolated enum ClickType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// Default left click.
    case unspecified // = 0

    /// Left mouse button.
    case left // = 1

    /// Right mouse button.
    case right // = 2

    /// Middle mouse button.
    case middle // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .left
      case 2: self = .right
      case 3: self = .middle
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .left: return 1
      case .right: return 2
      case .middle: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Exactmac_V1_MouseClick.ClickType] = [
      .unspecified,
      .left,
      .right,
      .middle,
    ]

  }

  public init() {}

  fileprivate var _position: Exactmac_Type_Point? = nil
  fileprivate var _clickType: Exactmac_V1_MouseClick.ClickType? = nil
  fileprivate var _clickCount: Int32? = nil
}

/// Text input action.
public nonisolated struct Exactmac_V1_TextInput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Text to type.
  public var text: String = String()

  /// Delay between characters in seconds.
  public var charDelay: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Key press with optional modifiers.
public nonisolated struct Exactmac_V1_KeyPress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Key code or name (e.g., "return", "a", "f1").
  public var key: String = String()

  /// Modifier keys to hold during press.
  public var modifiers: [Exactmac_V1_KeyPress.Modifier] = []

  /// Duration to hold the key in seconds. If 0 or unset, performs a normal press/release.
  public var holdDuration: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Modifier key enumeration.
  public nonisolated enum Modifier: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// Default unspecified modifier.
    case unspecified // = 0

    /// Command (⌘) key.
    case command // = 1

    /// Option (⌥) key.
    case option // = 2

    /// Control (⌃) key.
    case control // = 3

    /// Shift (⇧) key.
    case shift // = 4

    /// Function (fn) key.
    case function // = 5

    /// Caps Lock.
    case capsLock // = 6
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .command
      case 2: self = .option
      case 3: self = .control
      case 4: self = .shift
      case 5: self = .function
      case 6: self = .capsLock
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .command: return 1
      case .option: return 2
      case .control: return 3
      case .shift: return 4
      case .function: return 5
      case .capsLock: return 6
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Exactmac_V1_KeyPress.Modifier] = [
      .unspecified,
      .command,
      .option,
      .control,
      .shift,
      .function,
      .capsLock,
    ]

  }

  public init() {}
}

/// Mouse move action.
///
/// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
/// See exactmac.type.Point message documentation for detailed coordinate system explanation.
public nonisolated struct Exactmac_V1_MouseMove: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target position in Global Display Coordinates.
  public var position: Exactmac_Type_Point {
    get {_position ?? Exactmac_Type_Point()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  /// Duration of movement in seconds (for smooth animation).
  public var duration: Double = 0

  /// Modifier keys applied atomically to every movement event.
  public var modifiers: [Exactmac_V1_KeyPress.Modifier] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: Exactmac_Type_Point? = nil
}

/// Mouse drag action.
///
/// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
/// See exactmac.type.Point message documentation for detailed coordinate system explanation.
public nonisolated struct Exactmac_V1_MouseDrag: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Starting position in Global Display Coordinates.
  public var startPosition: Exactmac_Type_Point {
    get {_startPosition ?? Exactmac_Type_Point()}
    set {_startPosition = newValue}
  }
  /// Returns true if `startPosition` has been explicitly set.
  public var hasStartPosition: Bool {self._startPosition != nil}
  /// Clears the value of `startPosition`. Subsequent reads from it will return its default value.
  public mutating func clearStartPosition() {self._startPosition = nil}

  /// Ending position in Global Display Coordinates.
  public var endPosition: Exactmac_Type_Point {
    get {_endPosition ?? Exactmac_Type_Point()}
    set {_endPosition = newValue}
  }
  /// Returns true if `endPosition` has been explicitly set.
  public var hasEndPosition: Bool {self._endPosition != nil}
  /// Clears the value of `endPosition`. Subsequent reads from it will return its default value.
  public mutating func clearEndPosition() {self._endPosition = nil}

  /// Duration of drag in seconds.
  public var duration: Double = 0

  /// Mouse button to use for drag.
  public var button: Exactmac_V1_MouseClick.ClickType {
    get {_button ?? .unspecified}
    set {_button = newValue}
  }
  /// Returns true if `button` has been explicitly set.
  public var hasButton: Bool {self._button != nil}
  /// Clears the value of `button`. Subsequent reads from it will return its default value.
  public mutating func clearButton() {self._button = nil}

  /// Modifier keys applied atomically to every drag event.
  public var modifiers: [Exactmac_V1_KeyPress.Modifier] = []

  /// Ordered drag waypoints in Global Display Coordinates. When present, this
  /// field is authoritative and must contain at least two points. The first and
  /// last points must equal start_position and end_position when those fields
  /// are also supplied.
  public var waypoints: [Exactmac_Type_Point] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _startPosition: Exactmac_Type_Point? = nil
  fileprivate var _endPosition: Exactmac_Type_Point? = nil
  fileprivate var _button: Exactmac_V1_MouseClick.ClickType? = nil
}

/// Scroll action.
///
/// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
/// See exactmac.type.Point message documentation for detailed coordinate system explanation.
public nonisolated struct Exactmac_V1_Scroll: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Position to scroll at (optional, uses current mouse position if not set).
  /// In Global Display Coordinates.
  public var position: Exactmac_Type_Point {
    get {_position ?? Exactmac_Type_Point()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  /// Horizontal scroll amount (positive = right, negative = left).
  public var horizontal: Double = 0

  /// Vertical scroll amount (positive = up, negative = down).
  public var vertical: Double = 0

  /// Duration of scroll in seconds (for momentum effect).
  public var duration: Double = 0

  /// Modifier keys applied atomically to every scroll event.
  public var modifiers: [Exactmac_V1_KeyPress.Modifier] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: Exactmac_Type_Point? = nil
}

/// Hover action.
///
/// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
/// See exactmac.type.Point message documentation for detailed coordinate system explanation.
public nonisolated struct Exactmac_V1_Hover: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Position to hover at in Global Display Coordinates.
  public var position: Exactmac_Type_Point {
    get {_position ?? Exactmac_Type_Point()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  /// Duration to hover in seconds.
  public var duration: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: Exactmac_Type_Point? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "exactmac.v1"

nonisolated extension Exactmac_V1_Input: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Input"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}action\0\u{1}state\0\u{3}create_time\0\u{3}complete_time\0\u{1}error\0\u{1}target\0\u{3}delivery_result\0")

  fileprivate class _StorageClass {
    var _name: String = String()
    var _action: Exactmac_V1_InputAction? = nil
    var _state: Exactmac_V1_Input.State = .unspecified
    var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _completeTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _error: String = String()
    var _target: Exactmac_V1_InputTarget? = nil
    var _deliveryResult: Exactmac_V1_InputDeliveryResult? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _action = source._action
      _state = source._state
      _createTime = source._createTime
      _completeTime = source._completeTime
      _error = source._error
      _target = source._target
      _deliveryResult = source._deliveryResult
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._action) }()
        case 3: try { try decoder.decodeSingularEnumField(value: &_storage._state) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._createTime) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._completeTime) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._error) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._target) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._deliveryResult) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      try { if let v = _storage._action {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if _storage._state != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._state, fieldNumber: 3)
      }
      try { if let v = _storage._createTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._completeTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._error.isEmpty {
        try visitor.visitSingularStringField(value: _storage._error, fieldNumber: 6)
      }
      try { if let v = _storage._target {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._deliveryResult {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_Input, rhs: Exactmac_V1_Input) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._action != rhs_storage._action {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._createTime != rhs_storage._createTime {return false}
        if _storage._completeTime != rhs_storage._completeTime {return false}
        if _storage._error != rhs_storage._error {return false}
        if _storage._target != rhs_storage._target {return false}
        if _storage._deliveryResult != rhs_storage._deliveryResult {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_Input.State: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATE_UNSPECIFIED\0\u{1}STATE_PENDING\0\u{1}STATE_EXECUTING\0\u{1}STATE_COMPLETED\0\u{1}STATE_FAILED\0\u{1}STATE_CANCELLED\0")
}

nonisolated extension Exactmac_V1_InputTarget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputTarget"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}application\0\u{1}window\0\u{1}display\0\u{1}desktop\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.destination != nil {try decoder.handleConflictingOneOf()}
          self.destination = .application(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.destination != nil {try decoder.handleConflictingOneOf()}
          self.destination = .window(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.destination != nil {try decoder.handleConflictingOneOf()}
          self.destination = .display(v)
        }
      }()
      case 4: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.destination != nil {try decoder.handleConflictingOneOf()}
          self.destination = .desktop(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.destination {
    case .application?: try {
      guard case .application(let v)? = self.destination else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .window?: try {
      guard case .window(let v)? = self.destination else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .display?: try {
      guard case .display(let v)? = self.destination else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case .desktop?: try {
      guard case .desktop(let v)? = self.destination else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_InputTarget, rhs: Exactmac_V1_InputTarget) -> Bool {
    if lhs.destination != rhs.destination {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_InputDeliveryResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputDeliveryResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}commitment\0\u{3}posted_event_count\0\u{3}routed_delivery_observed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.commitment) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.postedEventCount) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.routedDeliveryObserved) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.commitment != .unspecified {
      try visitor.visitSingularEnumField(value: self.commitment, fieldNumber: 1)
    }
    if self.postedEventCount != 0 {
      try visitor.visitSingularInt32Field(value: self.postedEventCount, fieldNumber: 2)
    }
    if self.routedDeliveryObserved != false {
      try visitor.visitSingularBoolField(value: self.routedDeliveryObserved, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_InputDeliveryResult, rhs: Exactmac_V1_InputDeliveryResult) -> Bool {
    if lhs.commitment != rhs.commitment {return false}
    if lhs.postedEventCount != rhs.postedEventCount {return false}
    if lhs.routedDeliveryObserved != rhs.routedDeliveryObserved {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_InputDeliveryResult.Commitment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COMMITMENT_UNSPECIFIED\0\u{1}COMMITMENT_NO_EFFECT\0\u{1}COMMITMENT_POSSIBLY_COMMITTED\0\u{1}COMMITMENT_COMMITTED_AND_SETTLED\0")
}

nonisolated extension Exactmac_V1_InputAction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputAction"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}visual_feedback\0\u{3}animation_duration\0\u{3}mouse_click\0\u{3}text_input\0\u{3}key_press\0\u{3}mouse_move\0\u{3}mouse_drag\0\u{3}scroll_action\0\u{3}hover_action\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.visualFeedback) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.animationDuration) }()
      case 3: try {
        var v: Exactmac_V1_MouseClick?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .mouseClick(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .mouseClick(v)
        }
      }()
      case 4: try {
        var v: Exactmac_V1_TextInput?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .textInput(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .textInput(v)
        }
      }()
      case 5: try {
        var v: Exactmac_V1_KeyPress?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .keyPress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .keyPress(v)
        }
      }()
      case 6: try {
        var v: Exactmac_V1_MouseMove?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .mouseMove(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .mouseMove(v)
        }
      }()
      case 7: try {
        var v: Exactmac_V1_MouseDrag?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .mouseDrag(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .mouseDrag(v)
        }
      }()
      case 8: try {
        var v: Exactmac_V1_Scroll?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .scrollAction(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .scrollAction(v)
        }
      }()
      case 9: try {
        var v: Exactmac_V1_Hover?
        var hadOneofValue = false
        if let current = self.inputType {
          hadOneofValue = true
          if case .hoverAction(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputType = .hoverAction(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.visualFeedback != false {
      try visitor.visitSingularBoolField(value: self.visualFeedback, fieldNumber: 1)
    }
    if self.animationDuration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.animationDuration, fieldNumber: 2)
    }
    switch self.inputType {
    case .mouseClick?: try {
      guard case .mouseClick(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .textInput?: try {
      guard case .textInput(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .keyPress?: try {
      guard case .keyPress(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .mouseMove?: try {
      guard case .mouseMove(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .mouseDrag?: try {
      guard case .mouseDrag(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .scrollAction?: try {
      guard case .scrollAction(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .hoverAction?: try {
      guard case .hoverAction(let v)? = self.inputType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_InputAction, rhs: Exactmac_V1_InputAction) -> Bool {
    if lhs.visualFeedback != rhs.visualFeedback {return false}
    if lhs.animationDuration != rhs.animationDuration {return false}
    if lhs.inputType != rhs.inputType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_MouseClick: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MouseClick"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{3}click_type\0\u{3}click_count\0\u{1}modifiers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._clickType) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._clickCount) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.modifiers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._clickType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._clickCount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    if !self.modifiers.isEmpty {
      try visitor.visitPackedEnumField(value: self.modifiers, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_MouseClick, rhs: Exactmac_V1_MouseClick) -> Bool {
    if lhs._position != rhs._position {return false}
    if lhs._clickType != rhs._clickType {return false}
    if lhs._clickCount != rhs._clickCount {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_MouseClick.ClickType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CLICK_TYPE_UNSPECIFIED\0\u{1}CLICK_TYPE_LEFT\0\u{1}CLICK_TYPE_RIGHT\0\u{1}CLICK_TYPE_MIDDLE\0")
}

nonisolated extension Exactmac_V1_TextInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TextInput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}char_delay\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.charDelay) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    if self.charDelay.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.charDelay, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_TextInput, rhs: Exactmac_V1_TextInput) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.charDelay != rhs.charDelay {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_KeyPress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyPress"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}modifiers\0\u{3}hold_duration\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeRepeatedEnumField(value: &self.modifiers) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.holdDuration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.modifiers.isEmpty {
      try visitor.visitPackedEnumField(value: self.modifiers, fieldNumber: 2)
    }
    if self.holdDuration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.holdDuration, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_KeyPress, rhs: Exactmac_V1_KeyPress) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.holdDuration != rhs.holdDuration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_KeyPress.Modifier: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MODIFIER_UNSPECIFIED\0\u{1}MODIFIER_COMMAND\0\u{1}MODIFIER_OPTION\0\u{1}MODIFIER_CONTROL\0\u{1}MODIFIER_SHIFT\0\u{1}MODIFIER_FUNCTION\0\u{1}MODIFIER_CAPS_LOCK\0")
}

nonisolated extension Exactmac_V1_MouseMove: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MouseMove"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{1}duration\0\u{1}modifiers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.duration) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.modifiers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.duration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 2)
    }
    if !self.modifiers.isEmpty {
      try visitor.visitPackedEnumField(value: self.modifiers, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_MouseMove, rhs: Exactmac_V1_MouseMove) -> Bool {
    if lhs._position != rhs._position {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_MouseDrag: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MouseDrag"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_position\0\u{3}end_position\0\u{1}duration\0\u{1}button\0\u{1}modifiers\0\u{1}waypoints\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._startPosition) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._endPosition) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.duration) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._button) }()
      case 5: try { try decoder.decodeRepeatedEnumField(value: &self.modifiers) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.waypoints) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._startPosition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._endPosition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.duration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 3)
    }
    try { if let v = self._button {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    if !self.modifiers.isEmpty {
      try visitor.visitPackedEnumField(value: self.modifiers, fieldNumber: 5)
    }
    if !self.waypoints.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.waypoints, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_MouseDrag, rhs: Exactmac_V1_MouseDrag) -> Bool {
    if lhs._startPosition != rhs._startPosition {return false}
    if lhs._endPosition != rhs._endPosition {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs._button != rhs._button {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.waypoints != rhs.waypoints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_Scroll: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Scroll"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{1}horizontal\0\u{1}vertical\0\u{1}duration\0\u{1}modifiers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.horizontal) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.vertical) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.duration) }()
      case 5: try { try decoder.decodeRepeatedEnumField(value: &self.modifiers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.horizontal.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.horizontal, fieldNumber: 2)
    }
    if self.vertical.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.vertical, fieldNumber: 3)
    }
    if self.duration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 4)
    }
    if !self.modifiers.isEmpty {
      try visitor.visitPackedEnumField(value: self.modifiers, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_Scroll, rhs: Exactmac_V1_Scroll) -> Bool {
    if lhs._position != rhs._position {return false}
    if lhs.horizontal != rhs.horizontal {return false}
    if lhs.vertical != rhs.vertical {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_Hover: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Hover"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{1}duration\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.duration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.duration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_Hover, rhs: Exactmac_V1_Hover) -> Bool {
    if lhs._position != rhs._position {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
