// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: exactmac/v1/window.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Joseph Cumines
//
// Window resource definition

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A resource representing an individual window within an application.
/// Contains only cheap CoreGraphics data. For expensive AX state queries,
/// use GetWindowState to fetch the WindowState singleton sub-resource.
public nonisolated struct Exactmac_V1_Window: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Resource name in the format "applications/{application}/windows/{window}"
  /// where {application} identifies one exact kernel process instance and
  /// {window} is a server-generated opaque ID for one live window generation.
  /// Clients must not parse either ID or substitute a Core Graphics window ID.
  public var name: String = String()

  /// The title of the window.
  ///
  /// Data Source (Hybrid Authority):
  ///   - ListWindows: Returns Quartz-cached title (kCGWindowName) for performance.
  ///   - GetWindow / Mutation responses: Fresh Accessibility API query (kAXTitleAttribute).
  public var title: String = String()

  /// Bounding rectangle of the window.
  ///
  /// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
  /// See exactmac.type.Point message documentation for detailed coordinate system explanation.
  ///
  /// Data Source (AX Authority): Fresh Accessibility API queries (kAXPositionAttribute, kAXSizeAttribute).
  /// These fields are queried from AX on every request. Mutation RPCs return
  /// only after observed AX readback reaches its documented steady state.
  public var bounds: Exactmac_V1_Bounds {
    get {_bounds ?? Exactmac_V1_Bounds()}
    set {_bounds = newValue}
  }
  /// Returns true if `bounds` has been explicitly set.
  public var hasBounds: Bool {self._bounds != nil}
  /// Clears the value of `bounds`. Subsequent reads from it will return its default value.
  public mutating func clearBounds() {self._bounds = nil}

  /// Whether the window is currently visible on screen.
  ///
  /// Data Source (Hybrid Authority - Differs by RPC):
  ///
  /// GetWindow (AX-Validated Visibility):
  ///   Computes visible using fresh, error-preserving AX queries:
  ///     visible = registry.isOnScreen && !axMinimized && !ownerApplicationHidden
  ///
  ///   Visibility is true only when the admitted Core Graphics snapshot reports
  ///   the window on-screen and fresh AX state reports neither the window
  ///   minimized nor its owner hidden. Missing or malformed AX values fail the
  ///   request; the server never fabricates visible=true.
  ///
  /// ListWindows (Registry-Only Performance):
  ///   Returns registry.isOnScreen directly from cached CGWindowList with NO per-window AX queries.
  ///   This performs no per-window AX queries; latency depends on snapshot size and system conditions.
  ///   Registry data is a volatile snapshot and may lag actual state during rapid window mutations.
  ///
  /// Recommendation:
  ///   - Use ListWindows for fast enumeration and UI rendering
  ///   - Use GetWindow for authoritative visibility after mutations
  ///   - Use GetWindowState for expensive AX state details (modal, focused, etc.)
  public var visible: Bool = false

  /// Bundle identifier of the application that owns this window.
  ///
  /// Data Source (Registry Authority): Resolved via NSRunningApplication from cached CGWindowList metadata.
  /// This is snapshot metadata and may be empty when resolution is unavailable.
  /// Empty string if NSRunningApplication resolution fails or registry data is unavailable.
  public var bundleID: String = String()

  /// Core Graphics window layer from kCGWindowLayer.
  ///
  /// This is a compositing layer, not a z-order index. Multiple windows may
  /// share the same layer; clients must not infer front-to-back order from it.
  public var layer: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _bounds: Exactmac_V1_Bounds? = nil
}

/// Bounding rectangle for window positioning.
///
/// COORDINATE SYSTEM: Global Display Coordinates (top-left origin, Y increases downward).
/// See exactmac.type.Point message documentation for detailed coordinate system explanation.
public nonisolated struct Exactmac_V1_Bounds: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// X coordinate of the window's origin in Global Display Coordinates.
  public var x: Double = 0

  /// Y coordinate of the window's origin in Global Display Coordinates.
  public var y: Double = 0

  /// Width of the window in logical display points.
  public var width: Double = 0

  /// Height of the window in logical display points.
  public var height: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Detailed state information about a window, fetched via expensive AX queries.
/// This is a singleton sub-resource that clients must explicitly request.
/// Use GetWindowState to fetch this data on-demand.
public nonisolated struct Exactmac_V1_WindowState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Resource name in the format "applications/{application}/windows/{window}/state"
  public var name: String = String()

  /// Whether the window can be resized.
  ///
  /// Data Source: AXUIElementIsAttributeSettable for kAXSizeAttribute.
  /// This is an expensive query that should only be fetched on-demand via GetWindowState.
  public var resizable: Bool = false

  /// Whether the window can be minimized.
  ///
  /// Data Source: AX query checking existence of AXMinimizeButton attribute.
  /// This is an expensive query that should only be fetched on-demand via GetWindowState.
  public var minimizable: Bool = false

  /// Whether the window can be closed.
  ///
  /// Data Source: AX query checking existence of AXCloseButton attribute.
  /// This is an expensive query that should only be fetched on-demand via GetWindowState.
  public var closable: Bool = false

  /// Whether the window is a modal dialog.
  ///
  /// Data Source: AX queries of kAXModalAttribute and kAXSubroleAttribute.
  /// True if explicitly marked modal or the exact subrole is AXDialog or AXSystemDialog.
  /// This is an expensive query that should only be fetched on-demand via GetWindowState.
  public var modal: Bool = false

  /// Whether the window is a floating window.
  ///
  /// Data Source: AX query of kAXSubroleAttribute.
  /// True if the exact subrole is AXFloatingWindow or AXSystemFloatingWindow.
  /// This is an expensive query that should only be fetched on-demand via GetWindowState.
  public var floating: Bool = false

  /// Whether the window's owner application is explicitly hidden according to AX.
  ///
  /// Data Source: Fresh kAXHiddenAttribute query on the owner application element.
  /// True means the owner application is hidden (NOT that this window is minimized to dock).
  /// This field is distinct from:
  ///   - Window.visible (hybrid formula combining registry + AX state)
  ///   - minimized (window is in dock, not explicitly hidden)
  ///
  /// Note: This field is ALSO queried in Window responses (as part of the visible formula),
  /// but Window responses may use cached registry data for performance. GetWindowState
  /// guarantees a fresh AX query.
  public var axHidden: Bool = false

  /// Whether the window is minimized (in the dock).
  ///
  /// Data Source: Fresh AX query of kAXMinimizedAttribute.
  /// True means the window is minimized to the dock (NOT explicitly hidden).
  ///
  /// Note: This field is ALSO queried in Window responses (as part of the visible formula),
  /// but clients requiring authoritative minimized state should use GetWindowState to ensure
  /// the most up-to-date value, especially immediately after minimize/restore operations.
  public var minimized: Bool = false

  /// Whether the window is focused (is the main window).
  ///
  /// Data Source: Fresh AX query of kAXMainAttribute.
  /// True if this window is the application's main (focused) window.
  /// This is an expensive query that should only be fetched on-demand via GetWindowState.
  public var focused: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "exactmac.v1"

nonisolated extension Exactmac_V1_Window: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Window"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}title\0\u{1}bounds\0\u{2}\u{2}visible\0\u{4}\u{5}bundle_id\0\u{1}layer\0\u{b}z_index\0\u{c}\u{4}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._bounds) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.visible) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.bundleID) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self.layer) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    try { if let v = self._bounds {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.visible != false {
      try visitor.visitSingularBoolField(value: self.visible, fieldNumber: 5)
    }
    if !self.bundleID.isEmpty {
      try visitor.visitSingularStringField(value: self.bundleID, fieldNumber: 10)
    }
    if self.layer != 0 {
      try visitor.visitSingularInt32Field(value: self.layer, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_Window, rhs: Exactmac_V1_Window) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.title != rhs.title {return false}
    if lhs._bounds != rhs._bounds {return false}
    if lhs.visible != rhs.visible {return false}
    if lhs.bundleID != rhs.bundleID {return false}
    if lhs.layer != rhs.layer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_Bounds: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Bounds"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.y) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.width) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.y, fieldNumber: 2)
    }
    if self.width.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.width, fieldNumber: 3)
    }
    if self.height.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_Bounds, rhs: Exactmac_V1_Bounds) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Exactmac_V1_WindowState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WindowState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}resizable\0\u{1}minimizable\0\u{1}closable\0\u{1}modal\0\u{1}floating\0\u{3}ax_hidden\0\u{1}minimized\0\u{1}focused\0\u{b}fullscreen\0\u{c}\u{a}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.resizable) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.minimizable) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.closable) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.modal) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.floating) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.axHidden) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.minimized) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.focused) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.resizable != false {
      try visitor.visitSingularBoolField(value: self.resizable, fieldNumber: 2)
    }
    if self.minimizable != false {
      try visitor.visitSingularBoolField(value: self.minimizable, fieldNumber: 3)
    }
    if self.closable != false {
      try visitor.visitSingularBoolField(value: self.closable, fieldNumber: 4)
    }
    if self.modal != false {
      try visitor.visitSingularBoolField(value: self.modal, fieldNumber: 5)
    }
    if self.floating != false {
      try visitor.visitSingularBoolField(value: self.floating, fieldNumber: 6)
    }
    if self.axHidden != false {
      try visitor.visitSingularBoolField(value: self.axHidden, fieldNumber: 7)
    }
    if self.minimized != false {
      try visitor.visitSingularBoolField(value: self.minimized, fieldNumber: 8)
    }
    if self.focused != false {
      try visitor.visitSingularBoolField(value: self.focused, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Exactmac_V1_WindowState, rhs: Exactmac_V1_WindowState) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.resizable != rhs.resizable {return false}
    if lhs.minimizable != rhs.minimizable {return false}
    if lhs.closable != rhs.closable {return false}
    if lhs.modal != rhs.modal {return false}
    if lhs.floating != rhs.floating {return false}
    if lhs.axHidden != rhs.axHidden {return false}
    if lhs.minimized != rhs.minimized {return false}
    if lhs.focused != rhs.focused {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
