// Copyright 2025 Joseph Cumines
//
// Common geometric types

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: macosusesdk/type/geometry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

// This file contained no services.
